name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # This installs Gradle automatically so you don't need a gradlew file
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Application
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-App
          path: app/build/outputs/apk/debug/app-debug.apk

  test:
    name: Test Application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # This installs Gradle for your test stage too
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test Application
        run: gradle test

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: Android-App
          path: apk

      - name: Deploy Application
        run: echo "Application deployed successfully"
